scrape_configs:
  - job_name: 'apigateway'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1s # This can be adjusted based on our needs
    static_configs:
      - targets: ['192.168.30.143:8080']